-- AtlasQL core schema.
--
-- Design notes that are not obvious from the DDL:
--
--   * regions.(source, source_id) is the natural key every ETL job upserts on,
--     so ids stay stable across re-imports and metrics never orphan.
--   * regions.geom is NULL for point-only tiers (cities), which carry only a
--     centroid. Polygon tiers carry both.
--   * metrics.year is NOT NULL because it is part of the primary key. Metrics
--     that are not a time series still record the vintage of the source they
--     came from (GMTED2010 -> 2010), so importing a newer vintage adds a row
--     instead of silently overwriting a differently dated measurement.
--   * metric_definitions is the live registry that /metadata reads and that the
--     natural language parser is re-validated against. An unregistered metric
--     cannot be stored.

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS regions (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      TEXT NOT NULL,
  level     TEXT NOT NULL CHECK (level IN ('continent','country','state','county','city')),
  parent_id BIGINT REFERENCES regions(id),
  source    TEXT NOT NULL,
  source_id TEXT NOT NULL,
  geom      GEOMETRY(MultiPolygon, 4326),
  centroid  GEOMETRY(Point, 4326),
  UNIQUE (source, source_id)
);

CREATE INDEX IF NOT EXISTS idx_regions_level  ON regions(level);
CREATE INDEX IF NOT EXISTS idx_regions_parent ON regions(parent_id);
CREATE INDEX IF NOT EXISTS idx_regions_geom   ON regions USING GIST(geom);

CREATE TABLE IF NOT EXISTS metric_definitions (
  metric_name TEXT PRIMARY KEY,
  label       TEXT NOT NULL,
  unit        TEXT,
  description TEXT,
  source      TEXT
);

CREATE TABLE IF NOT EXISTS metrics (
  region_id   BIGINT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
  metric_name TEXT NOT NULL REFERENCES metric_definitions(metric_name),
  value       DOUBLE PRECISION,
  year        INT NOT NULL,
  PRIMARY KEY (region_id, metric_name, year)
);

CREATE INDEX IF NOT EXISTS idx_metrics_name_value ON metrics(metric_name, value);

-- Derived table, recomputed after every ETL run. Level auto-detection reads
-- this and nothing else, so a stale row silently changes query semantics --
-- hence computed_at.
CREATE TABLE IF NOT EXISTS metric_availability (
  metric_name  TEXT NOT NULL,
  level        TEXT NOT NULL,
  coverage_pct DOUBLE PRECISION NOT NULL,
  computed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (metric_name, level)
);
